[package]
name = "scheme"
version = "0.1.0"
authors = ["Itai Bar-Natan <itaibn3141@gmail.com>"]

[dependencies]
either = "1.5.0"
gc = "*"
gc_derive = "*"
lazy_static = "1.0.0"
maplit = "1.0.1"
#nom = {version = "3.2.0", features = ["regexp"]}
num = "0.3.1"
regex = "0.2"
